### PR TITLE
Add min pin

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Sorry, missed that the last time.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Review by tkralphs — APPROVED** [review]
Looks like there is one conda-related change of substance, so I would leave this to @wolfv to assess and merge.

**Comment by BastianZim** [comment]
@tkralphs Of course, fully understood. Just to explain: YAML files use two spaces to indent and I used 4 (Which is used by python) which I'm correcting here. 
That's really the only change, the rest comes from rerendering which is done by conda-forge.  

The two space indent was also used in all of the other patches (Example: https://github.com/conda-forge/coin-or-cbc-feedstock/pull/9)

**Comment by tkralphs** [comment]
I got that part, but you also deleted `defaults` under `channel_sources` and that was the part I didn't know how to assess.

**Comment by BastianZim** [comment]
Ahh ok, that wasn’t actually done by me, it comes from the rerendering and was caused by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1954. That's conda infrastructure-related and will be done with all feedstocks when they get rerendered (https://github.com/conda-forge/coin-or-osi-feedstock/pull/4/commits/dcdaabed897b86e392821370e371f7ed5d00387c).
But let's wait for @wolfv and be on the safe side.

**Comment by BastianZim** [comment]
@wolfv When you have a sec, would you mind merging this and https://github.com/conda-forge/coin-or-clp-feedstock/pull/6

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Review by tkralphs — APPROVED** [review]
Looks good!

**Comment by BastianZim** [comment]
@tkralphs I think @wolfv is quite busy right now with packaging-con. Do you have someone else at conda-forge that you'd be happy to have this reviewed by or do you feel comfortable merging this yourself?

**Pull request merged**
