### PR TITLE
Add windows build

### PR DESCRIPTION
**Pull request by jpfeuffer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

related to https://github.com/conda-forge/coin-or-cbc-feedstock/issues/3

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@conda-forge-admin, please rerender

**Comment by jpfeuffer** [comment]
@conda-forge-admin, please rerender

**Comment by jpfeuffer** [comment]
@tkralphs On Windows I cannot make it find CoinUtils.
On Linux and macOS the tests segfault if I give them the c versions of blas and lapack

**Comment by tkralphs** [comment]
Argh, yeah, for Windows, there is an issue. It first tries to find the CoinUtils installation via `pkg-config`, but this doesn't work on Windows. It then falls back to looking for it in some default locations and doesn't find it there either. This is all works fine with a monolithic build using coinbrew, but in this setup, it should be looking in the location where conda installs CoinUtils. I guess we need to specify the install location explicitly with `--with-coinutils-lib` and `--with-coinutils-incdir`, but I'm honestly not sure exactly how to do that in Windows, since those arguments should get passed to the Visual Studio compiler and the arguments are different than the ones for gcc.

**Comment by tkralphs** [comment]
OK! So it found the library and we able to link to it in the configure step, but now the `\`'s are being stripped out out of the include path: `-ID:bldcoin-or-osi_1723810316376_h_envLibraryincludecoin`. Maybe quoting works?

**Comment by jpfeuffer** [comment]
@tkralphs Ok, now I get
`make[2]: *** No rule to make target 'D:/bld/coin-or-osi_1723816981747/_h_env/Library/lib/CoinUtils.lib', needed by 'unitTest.exe'.  Stop.` for the unitTest in the end.

**Comment by jpfeuffer** [comment]
Unfortunately, it feels like both remaining problems (segfault tests on unix and misinterpreting makefile on windows) cannot be solved easily in the conda recipe and would need some investigation on the library developer side.

**Comment by tkralphs** [comment]
OK, I will take a look. The failure on Windows is strange, but must be a hiccup in the build system. I can't see how we can be getting seg faults on the other platforms.

**Comment by jpfeuffer** [comment]
On Linux:
Observations: 
- although it accepts the with-blas/lack flags it does not use what's specified in them on the linker command line (at least not in the regular stdout logs). It succeeds to compile though.
- the tests also complain about missing test files

**Comment by tkralphs** [comment]
OK, thanks for the pointers.

**Comment by jpfeuffer** [comment]
@tkralphs Did you have any chance to look into the errors? I opened a new PR to update it to the newest version of the recipe.

**Pull request closed without merging**
